### ISSUE TITLE
Check motion complete on motor move

### ISSUE THREAD

**Issue by arrellc** [paulscherrerinstitute/photodiag_web#3]
Calibration routine can fail as motor may not move for different reasons

![image](https://user-images.githubusercontent.com/33692029/205496948-26ab5fde-c87c-4f24-8a4c-b9c6aa4fa57d.png)

Can the following be included in a motor move function (would likely also be needed for future apps)

- Check motion compete i.e check readback position has changed as expected
- Check motion is possible before attempt by checking motor soft limits

And and error displayed is a move is not possible or not completed

Motor soft limits are given by the PVs:
SAROP21-PBPS103:MOTOR_X1.HLM
SAROP21-PBPS103:MOTOR_X1.LLM

**Comment by ivan-usov** [comment]
Hi @arrellc , is there a separate readback position PV? Otherwise, I believe that `pv.put(..., wait=True)` already solves the first point.

**Comment by arrellc** [comment]
A readback PV is:
SARFE10-PBPS053:MOTOR_X1.RBV

and a motion complete flag is:

SARFE10-PBPS053:MOTOR_X1.MSTA

but I don't think the flag changes when soft limits are violated
