### ISSUE TITLE
Axis label for Jitter and correlation plots

### ISSUE THREAD

**Issue by arrellc** [paulscherrerinstitute/photodiag_web#4]
Can the label axis be the channel name e.g if device is SARFE10-PBPS053
XPOS => SARFE10-PBPS053:XPOS
YPOS => SARFE10-PBPS053:YPOS
INT=> SARFE10-PBPS053:INTENSITY

and the same for the correlation plot but where the device and device#2 are specified

**Comment by ivan-usov** [comment]
OK, but then it would also make sense to change the axes' labels on the calibration plots for consistency, i.e. 
MOTOR_X1.VAL => SARFE10-PBPS053:MOTOR_X1.VAL
MOTOR_Y1.VAL => SARFE10-PBPS053:MOTOR_Y1.VAL

Then, the plots' titles don't need to include a device name anymore, but only a timestamp, which I can also add to jitter and correlation plots. Do you have anything even better in mind?

**Comment by arrellc** [comment]
True, but I would keep the device name and time stamp in the plots, in reads easily
