### ISSUE TITLE
Autocorrelation of spectral signals

### ISSUE THREAD

**Issue by arrellc** [paulscherrerinstitute/photodiag_web#9]
A clear requirement from both the machine operators and users is to have an online spectral autocorrelation signal.  This is a key requirement to support the development of advanced modes at both Aramis and Athos.

As discussed the request is the follow:

- [x] Online autocorrelation signal with fit of 3 Gaussian and time plot of these evolution
- [x] Ability to optimise spectral device motors to confirm best performance 

Proposed layout (can be changed as required) is sketched here:
https://docs.google.com/presentation/d/1f-SCYxt3nC02LBlhhaHUeYCvRAIvsxK7-dzXQMkg_OE/edit?usp=sharing

and example code in from jupyter notebook sent by email.

**Comment by arrellc** [comment]
Improvement from 20.06.23

- [x] Remove limits on sigma
- [x] sort sigma by size
- [x] add heuristics for initial sigma guess
    - Background FWHM = 60% SPECTRUM_X range *1.4
    - Spectral envelop average caget device name: FIT-FWHM (20 shots) checked every 5 mins
    - The old naming for FWHM is :SPECTRUM_FWHM - this is running on PMOSs for now
    - Guess for spike width FWHM =1 eV*1.4
 - [x] When scanning, add a stop button which returns to initial value before scan was starting
 - [x] When scanning plot on right updates when each scan step is completed
 - [x] Change push to elog title as Device name Autocorrelation fit results

**Comment by ivan-usov** [comment]
All items should be done now.
